### ISSUE TITLE
Documentation incorrect and unable to locate package

### ISSUE THREAD

**Issue by ghost** [digitalpieltd/grav-akismet#1]
The documentation on the readme should actually read as below, where message is the field of the content on your form. Note the akismet.php file actually refers to the parameter as content, not comment.

```
process:
    -
      akismet:
        name: name
        email: email
        content: message
```

Also in akismet.php, the final block of code below
```
if(!$result) {
	$event->stopPropagation();
	$this->grav['log']->info('Contact form submission failed Akismet spam check. Spam author: ' . $form->data[$params['email']]);
	return;
}
```

Should actually read as below, because curl is returning the text for the result, and true if the comment is spam.

```
if('true' == $result) {
...
```
